name: Hello GitHub Actions

on: [push]

jobs:
  say-hello: # on peut mettre ce qu'on veut
    runs-on: ubuntu-latest
    steps:
      - name: Affichage dâ€™un message
        run: echo "ðŸŽ‰ Hello GitHub Actions depuis le workflow !"